name: Build & Push Frontend Image

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write # GHCR에 푸시 권한

jobs:
  build-and-dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: Buildx 설정
        uses: docker/setup-buildx-action@v2

      - name: GHCR 로그인
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: 이미지 빌드 및 푸시
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            NEXT_PUBLIC_API_ENDPOINT=${{ secrets.NEXT_PUBLIC_API_ENDPOINT }}
          tags: |
            ghcr.io/hc-organizations/todo-frontend:latest
            ghcr.io/hc-organizations/todo-frontend:${{ github.sha }}

      - name: 배포 레포지토리 알림
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: hc-organizations/todo-deploy
          event-type: frontend-update
          client-payload: '{"service":"frontend"}'
          token: ${{ secrets.GHCR_PAT }}
